package com.c1games.terminal.algo.defend;

public class CSVString {

    public final static String ordinal_csv = "3,12,Turret,Build\n" +
            "19,10,Turret,Build\n" +
            "0,13,Wall,Build\n" +
            "1,13,Wall,Build\n" +
            "2,13,Wall,Build\n" +
            "3,13,Wall,Build\n" +
            "9,5,Wall,Build\n" +
            "26,13,Wall,Build\n" +
            "25,13,Wall,Build\n" +
            "24,13,Wall,Build\n" +
            "23,13,Wall,Build\n" +
            "22,13,Wall,Build\n" +
            "4,12,Wall,Build\n" +
            "5,11,Wall,Build\n" +
            "6,10,Wall,Build\n" +
            "7,9,Wall,Build\n" +
            "8,8,Wall,Build\n" +
            "9,7,Wall,Build\n" +
            "10,6,Wall,Build\n" +
            "11,5,Wall,Build\n" +
            "12,4,Wall,Build\n" +
            "13,3,Wall,Build\n" +
            "14,3,Wall,Build\n" +
            "15,4,Wall,Build\n" +
            "16,5,Wall,Build\n" +
            "17,6,Wall,Build\n" +
            "18,7,Wall,Build\n" +
            "19,8,Wall,Build\n" +
            "20,9,Wall,Build\n" +
            "27,13,Wall,Build\n" +
            "21,13,Wall,Build\n" +
            "20,13,Wall,Build\n" +
            "19,13,Wall,Build\n" +
            "19,12,Turret,Build\n" +
            "0,13,Wall,Upgrade\n" +
            "19,13,Wall,Upgrade\n" +
            "27,13,Wall,Upgrade\n" +
            "1,13,Wall,Upgrade\n" +
            "3,12,Turret,Upgrade\n" +
            "24,12,Turret,Build\n" +
            "20,12,Turret,Build\n" +
            "20,13,Wall,Upgrade\n" +
            "21,13,Wall,Upgrade\n" +
            "23,12,Turret,Build\n" +
            "22,13,Wall,Upgrade\n" +
            "23,13,Wall,Upgrade\n" +
            "19,12,Turret,Upgrade\n" +
            "26,13,Wall,Upgrade\n" +
            "25,13,Wall,Upgrade\n" +
            "24,13,Wall,Upgrade\n" +
            "2,13,Wall,Upgrade\n" +
            "3,13,Wall,Upgrade\n" +
            "21,9,Support,Build\n" +
            "20,8,Support,Build\n" +
            "19,7,Support,Build\n" +
            "19,9,Turret,Build\n" +
            "20,10,Turret,Build\n" +
            "21,12,Turret,Build\n" +
            "25,12,Turret,Build\n" +
            "19,10,Turret,Upgrade\n" +
            "20,12,Turret,Upgrade\n" +
            "21,12,Turret,Upgrade\n" +
            "20,10,Turret,Upgrade\n" +
            "24,12,Turret,Build\n" +
            "25,12,Turret,Upgrade\n" +
            "22,12,Turret,Build\n" +
            "18,6,Support,Build\n" +
            "17,5,Support,Build\n" +
            "16,4,Support,Build\n" +
            "15,3,Support,Build\n" +
            "4,11,Turret,Build\n" +
            "4,11,Turret,Upgrade\n" +
            "4,11,Turret,Upgrade";
}
